apiVersion: v1
data:
  aws-secret-key: eHh4
  aws-session-token: eHh4
  bitbucket-password: eHh4
  cf-password: eHh4
  clouddriver-keystore-password: Y2hhbmdlaXQ=
  datadog-apikey: eHh4
  datadog-appkey: eHh4
  dinghy-key-password: cGFzc3dvcmQ=
  echo-keystore-password: Y2hhbmdlaXQ=
  fiat-keystore-password: Y2hhbmdlaXQ=
  front50-keystore-password: Y2hhbmdlaXQ=
  gate-keystore-password: Y2hhbmdlaXQ=
  git-https-password: eHh4
  github-oauth-token: eHh4
  github-password: eHh4
  github-token: eHh4
  gitlab-token: eHh4
  googleOauthClientId: Y2hhbmdlbWU=
  googleOauthClientSecret: Y2hhbmdlbWU=
  grafanaDefaultPassword: YWRtaW4=
  grafanaDefaultUser: YWRtaW4=
  helm-token: eHh4
  http-password: eHh4
  igor-keystore-password: Y2hhbmdlaXQ=
  jenkins-token: eHh4
  kayenta-keystore-password: Y2hhbmdlaXQ=
  minioAccessKey: Y2hhbmdlbWU=
  mysqlCdMigratePassword: Y2hhbmdlbWU=
  mysqlCdPassword: Y2hhbmdlbWU=
  mysqlF50MigratePassword: Y2hhbmdlbWU=
  mysqlF50Password: Y2hhbmdlbWU=
  mysqlOrcaMigratePassword: Y2hhbmdlbWU=
  mysqlOrcaPassword: Y2hhbmdlbWU=
  mysqlRootPassword: Y2hhbmdlbWU=
  oauth-client-secret: eHh4
  orca-keystore-password: Y2hhbmdlaXQ=
  prometheus-password: eHh4
  redis-password: eHh4
  rosco-keystore-password: Y2hhbmdlaXQ=
  saml-keystore-pwd: eHh4
  secretfile-example: U2FtcGxlIHNlY3JldCBmaWxl
  slack-token: eHh4
  ssh-pk-passphrase: eHh4
  terraformer-key-password: cGFzc3dvcmQ=
  tlsKeyStorePassword: Y2hhbmdlbWU=
  twilio-token: eHh4
  vaultToken: eHh4
kind: Secret
metadata:
  creationTimestamp: null
  name: spin-secrets
  namespace: spinnaker
