AWSTemplateFormatVersion: "2010-09-09"
Description: "deploy an example workload into an existing kubernetes cluster"
Metadata:
  cfn-lint: { config: { ignore_checks: [W9002, W9003, W9004, W9006, E9007] } }
Parameters:
  KubeClusterName:
    Type: String
Resources:
  KubeManifestURLNSSpinnaker:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "default"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/spinnaker_ns.yml
  KubeManifestURLSpinSecrets:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "spinnaker"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/spin-secrets.yml
    DependsOn: "KubeManifestURLNSSpinnaker"
  KubeManifestURLSpinSA:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "spinnaker"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/spin-sa.yml
    DependsOn: "KubeManifestURLSpinSecrets"
  KubeManifestURLMYSQL:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "spinnaker"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/mysql.yml
    DependsOn: "KubeManifestURLSpinSA"
  KubeManifestURLRedis:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "spinnaker"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/redis.yml
    DependsOn: "KubeManifestURLMYSQL"
  KubeManifestURLNGINXIngress:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: "default"
      # Kubernetes manifest URL
      Url: https://raw.githubusercontent.com/mcgonagle/dryrun/main/nginx_ingress_deploy.yaml
    DependsOn: "KubeManifestURLRedis"